# Generated by Django 5.2.11 on 2026-06-19 02:18

import coldfront.core.utils
import coldfront.models.deletion
import coldfront.utils.jsonschema
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_customfield_required_action'),
        ('tenancy', '0003_tenant_custom_field_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlurmCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('schema', models.JSONField(blank=True, null=True, validators=[coldfront.utils.jsonschema.validate_schema], verbose_name='schema')),
                ('locked', models.BooleanField(default=False, help_text='Prevent users from submitting allocations for this resource.', verbose_name='locked')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slurm_clusters', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Slurm cluster',
                'verbose_name_plural': 'Slurm clusters',
                'ordering': ['name'],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SlurmPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated')),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('schema', models.JSONField(blank=True, null=True, validators=[coldfront.utils.jsonschema.validate_schema], verbose_name='schema')),
                ('locked', models.BooleanField(default=False, help_text='Prevent users from submitting allocations for this resource.', verbose_name='locked')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partitions', to='slurm.slurmcluster', verbose_name='cluster')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Slurm partition',
                'verbose_name_plural': 'Slurm partitions',
                'ordering': ['cluster__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'name'), name='slurm_slurmpartition_unique_cluster_name')],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
