# Generated by Django 6.0.6 on 2026-07-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import coldfront.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0011_savedfilter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("assigned_object_id", models.PositiveBigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=30,
                        verbose_name="kind",
                    ),
                ),
                ("comments", models.TextField(verbose_name="comments")),
                (
                    "assigned_object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "comment entry",
                "verbose_name_plural": "comment entries",
                "ordering": ("-created",),
                "indexes": [
                    models.Index(fields=["-created"], name="core_commen_created_973719_idx"),
                    models.Index(
                        fields=["assigned_object_type", "assigned_object_id"], name="core_commen_assigne_4f7609_idx"
                    ),
                ],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
