# Generated by Django 6.0.6 on 2026-07-25 19:20

import taggit.managers
from django.db import migrations, models

import coldfront.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_commententry"),
    ]

    operations = [
        migrations.AddField(
            model_name="commententry",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name="commententry",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.TaggedItem",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
