# Generated by Django 6.0.6 on 2026-07-25 22:55

from django.db import migrations, models

import coldfront.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0013_commententry_custom_field_data_commententry_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "link_text",
                    models.TextField(help_text="Jinja2 template code for link text", verbose_name="link text"),
                ),
                ("link_url", models.TextField(help_text="Jinja2 template code for link URL", verbose_name="link URL")),
                ("weight", models.PositiveSmallIntegerField(default=100, verbose_name="weight")),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        help_text="Links with the same group will appear as a dropdown menu",
                        max_length=50,
                        verbose_name="group name",
                    ),
                ),
                (
                    "button_class",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("teal", "Teal"),
                            ("cyan", "Cyan"),
                            ("gray", "Gray"),
                            ("black", "Black"),
                            ("white", "White"),
                            ("ghost-dark", "Link"),
                        ],
                        default="default",
                        help_text="The class of the first link in a group will be used for the dropdown button",
                        max_length=30,
                        verbose_name="button class",
                    ),
                ),
                (
                    "new_window",
                    models.BooleanField(
                        default=False, help_text="Force link to open in a new window", verbose_name="new window"
                    ),
                ),
                (
                    "object_types",
                    models.ManyToManyField(
                        help_text="The object type(s) to which this link applies.",
                        related_name="custom_links",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom link",
                "verbose_name_plural": "custom links",
                "ordering": ["group_name", "weight", "name"],
                "indexes": [
                    models.Index(fields=["group_name", "weight", "name"], name="core_custom_group_n_a053a2_idx")
                ],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
    ]
