# Generated by Django 6.0.6 on 2026-07-20 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_token_pepper_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="config", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "user preferences",
                "verbose_name_plural": "user preferences",
                "ordering": ["user"],
            },
        ),
    ]
