# Generated by Django 6.0.6 on 2026-08-03 02:06

import django.db.models.deletion
import django.db.models.functions.text
import mptt.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models

import coldfront.core.utils
import coldfront.models.deletion
import coldfront.models.fields
import coldfront.utils.jsonschema


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0014_customlink"),
        ("tenancy", "0003_tenant_custom_field_data_and_more"),
        ("users", "0008_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("slug", coldfront.models.fields.AutoSlugField(blank=True, unique=True, verbose_name="slug")),
                ("resource_object_id", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("active", "Active"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                            ("approved", "Approved"),
                            ("revoked", "Revoked"),
                            ("renew", "Renew"),
                        ],
                        default="requested",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="end date")),
                ("justification", models.TextField(blank=True, null=True, verbose_name="justification")),
                ("description", models.CharField(blank=True, max_length=200, null=True, verbose_name="description")),
                ("attribute_data", models.JSONField(blank=True, null=True, verbose_name="attributes")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocation",
                "verbose_name_plural": "allocations",
                "ordering": ["start_date"],
                "permissions": (
                    ("request", "Request allocation"),
                    ("approve", "Approve allocation"),
                    ("deny", "Deny allocation"),
                    ("activate", "Activate allocation"),
                    ("expire", "Expire allocation"),
                    ("revoke", "Revoke allocation"),
                    ("renew", "Renew allocation"),
                ),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AllocationChangeRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("slug", coldfront.models.fields.AutoSlugField(blank=True, unique=True, verbose_name="slug")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("applied", "Applied"),
                        ],
                        default="requested",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("justification", models.TextField(blank=True, verbose_name="justification")),
                (
                    "extension_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days to extend the allocation end_date. On apply, the end_date is increased by this many days.",
                        null=True,
                        verbose_name="extension (days)",
                    ),
                ),
                (
                    "attribute_changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON object containing only the keys that should change. On apply, these are merged into the allocation's attribute_data and validated against the resource schema.",
                        null=True,
                        verbose_name="attribute changes",
                    ),
                ),
                (
                    "extension_changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object mapping extension model paths to dicts of proposed field values. On apply, each extension's apply_json_change() is called with its proposed values.",
                        verbose_name="extension changes",
                    ),
                ),
                (
                    "snapshot_extension_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of extension field values at the time the change request was applied. Populated during the apply transition. Empty for unapplied requests.",
                        verbose_name="snapshot extension values",
                    ),
                ),
                (
                    "snapshot_attribute_values",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of allocation attribute_data at the time the change request was applied. Populated during the apply transition. Null for unapplied requests.",
                        null=True,
                        verbose_name="snapshot attribute values",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests",
                        to="ras.allocation",
                        verbose_name="allocation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_allocation_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_allocation_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewer",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocation change request",
                "verbose_name_plural": "allocation change requests",
                "ordering": ["created"],
                "permissions": (
                    ("request", "Request change"),
                    ("approve", "Approve change"),
                    ("deny", "Deny change"),
                    ("apply", "Apply change"),
                ),
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("slug", coldfront.models.fields.AutoSlugField(blank=True, unique=True, verbose_name="slug")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Group associated with this project. Users added to the project are automatically added to this group.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="users.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="allocation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="allocations", to="ras.project"
            ),
        ),
        migrations.CreateModel(
            name="ProjectUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="ras.project"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "project user",
                "verbose_name_plural": "project users",
                "ordering": ["id"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="slug")),
                ("color", coldfront.models.fields.ColorField(default="9e9e9e", max_length=6, verbose_name="color")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource type",
                "verbose_name_plural": "resource types",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, null=True, verbose_name="created")),
                ("last_updated", models.DateTimeField(auto_now=True, null=True, verbose_name="last updated")),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=coldfront.core.utils.CustomFieldJSONEncoder),
                ),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[coldfront.utils.jsonschema.validate_schema],
                        verbose_name="schema",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent users from submitting allocations for this resource.",
                        verbose_name="locked",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="slug")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("active", "Active"),
                            ("planned", "Planned"),
                            ("staged", "Staged"),
                            ("decommissioning", "Decommissioning"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ras.resource",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="core.TaggedItem",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="ras.resourcetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "generic resource",
                "verbose_name_plural": "generic resources",
                "ordering": ["name"],
            },
            bases=(coldfront.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["resource_object_type", "resource_object_id"], name="ras_allocat_resourc_ca8a1d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectuser",
            unique_together={("user", "project")},
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                models.F("tenant"),
                name="ras_resource_unique_name_parent_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                condition=models.Q(("tenant__isnull", True)),
                name="ras_resource_unique_name_parent",
                violation_error_message="Resource name must be unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True), ("tenant__isnull", True)),
                fields=("name",),
                name="ras_resource_name",
                violation_error_message="A top-level resource with this name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(fields=("parent", "slug"), name="ras_resource_parent_slug"),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="ras_resource_slug",
                violation_error_message="A top-level resource with this slug already exists.",
            ),
        ),
    ]
