# Generated by Django 6.0.6 on 2026-07-25 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ras", "0002_remove_project_status_project_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocation",
            name="comments",
        ),
    ]
