# Generated by Django 6.0.6 on 2026-07-27 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ras", "0003_remove_allocation_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allocation",
            options={
                "ordering": ["start_date"],
                "permissions": (
                    ("request", "Request allocation"),
                    ("approve", "Approve allocation"),
                    ("deny", "Deny allocation"),
                    ("activate", "Activate allocation"),
                    ("expire", "Expire allocation"),
                    ("revoke", "Revoke allocation"),
                    ("renew", "Renew allocation"),
                ),
                "verbose_name": "allocation",
                "verbose_name_plural": "allocations",
            },
        ),
    ]
