# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: Apache-2.0

from .allocations import (
    AllocationDeleteView,
    AllocationEditView,
    AllocationListView,
    AllocationTypeDeleteView,
    AllocationTypeEditView,
    AllocationTypeListView,
    AllocationTypeView,
    AllocationView,
)
from .projects import (
    ProjectAllocationTabView,
    ProjectDeleteView,
    ProjectEditView,
    ProjectListView,
    ProjectUserDeleteView,
    ProjectUserEditView,
    ProjectUserListView,
    ProjectUserTabView,
    ProjectUserView,
    ProjectView,
)
from .resources import (
    ResourceBulkImportView,
    ResourceDeleteView,
    ResourceEditView,
    ResourceListView,
    ResourceTypeBulkImportView,
    ResourceTypeDeleteView,
    ResourceTypeEditView,
    ResourceTypeListView,
    ResourceTypeView,
    ResourceView,
)

__all__ = (
    "AllocationDeleteView",
    "AllocationEditView",
    "AllocationListView",
    "AllocationTypeDeleteView",
    "AllocationTypeEditView",
    "AllocationTypeListView",
    "AllocationTypeView",
    "AllocationView",
    "AllocationTypeBulkImportView",
    "ProjectAllocationTabView",
    "ProjectUserTabView",
    "ProjectDeleteView",
    "ProjectEditView",
    "ProjectListView",
    "ProjectView",
    "ProjectUserDeleteView",
    "ProjectUserEditView",
    "ProjectUserListView",
    "ProjectUserView",
    "ResourceDeleteView",
    "ResourceEditView",
    "ResourceListView",
    "ResourceTypeDeleteView",
    "ResourceTypeEditView",
    "ResourceTypeListView",
    "ResourceTypeView",
    "ResourceView",
    "ResourceBulkImportView",
    "ResourceTypeBulkImportView",
)
